parameters:
    ne0heretic_firewall.admin.controller.class: Ne0Heretic\FirewallBundle\Controller\AdminController
    ne0heretic_firewall.frontend.controller.class: Ne0Heretic\FirewallBundle\Controller\FrontendController

services:
    _defaults:
        autowire: true
    Ne0Heretic\FirewallBundle\EventListener\KernelRequestListener:
        class: Ne0Heretic\FirewallBundle\EventListener\KernelListener
        arguments: ['@cache.redis', '%kernel.cache_dir%']
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest' }

    Ne0Heretic\FirewallBundle\EventListener\KernelResponseListener:
        class: Ne0Heretic\FirewallBundle\EventListener\KernelListener
        arguments: ['@cache.redis', '%kernel.cache_dir%']
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.response', method: 'onKernelResponse' }

    Ne0Heretic\FirewallBundle\Command\StoreDataCommand:
        class: Ne0Heretic\FirewallBundle\Command\StoreDataCommand
        arguments:
            - '@cache.redis'
            - '@doctrine'
        tags:
            - { name: console.command }
