ne0heretic_firewall.dashboard:
    path: /ne0heretic_firewall
    defaults:
        _controller: Ne0Heretic\FirewallBundle\Controller\AdminController::dashboardAction
    options:
        expose: true
